//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace housemanagement1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bhousemanagementEntities3 : DbContext
    {
        public bhousemanagementEntities3()
            : base("name=bhousemanagementEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerAccount> CustomerAccount { get; set; }
        public virtual DbSet<Payment3> Payment3 { get; set; }
        public virtual DbSet<Reservations> Reservations { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<AdminAccounts> AdminAccounts { get; set; }
    
        public virtual int InsertPayment2(string cardHolderName, Nullable<int> paymentAmount, Nullable<System.DateTime> expiryMonth)
        {
            var cardHolderNameParameter = cardHolderName != null ?
                new ObjectParameter("CardHolderName", cardHolderName) :
                new ObjectParameter("CardHolderName", typeof(string));
    
            var paymentAmountParameter = paymentAmount.HasValue ?
                new ObjectParameter("PaymentAmount", paymentAmount) :
                new ObjectParameter("PaymentAmount", typeof(int));
    
            var expiryMonthParameter = expiryMonth.HasValue ?
                new ObjectParameter("ExpiryMonth", expiryMonth) :
                new ObjectParameter("ExpiryMonth", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertPayment2", cardHolderNameParameter, paymentAmountParameter, expiryMonthParameter);
        }
    
        public virtual ObjectResult<MultiLogin1_Result> MultiLogin1(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MultiLogin1_Result>("MultiLogin1", usernameParameter, passwordParameter);
        }
    
        public virtual int SavePayment1(string cardHolderName, Nullable<int> paymentAmount, string expiryMonth)
        {
            var cardHolderNameParameter = cardHolderName != null ?
                new ObjectParameter("CardHolderName", cardHolderName) :
                new ObjectParameter("CardHolderName", typeof(string));
    
            var paymentAmountParameter = paymentAmount.HasValue ?
                new ObjectParameter("PaymentAmount", paymentAmount) :
                new ObjectParameter("PaymentAmount", typeof(int));
    
            var expiryMonthParameter = expiryMonth != null ?
                new ObjectParameter("ExpiryMonth", expiryMonth) :
                new ObjectParameter("ExpiryMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SavePayment1", cardHolderNameParameter, paymentAmountParameter, expiryMonthParameter);
        }
    
        public virtual ObjectResult<sp_GetAllReservations_Result_Result> sp_GetAllReservations_Result()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllReservations_Result_Result>("sp_GetAllReservations_Result");
        }
    
        public virtual int usp_Login(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Login", usernameParameter, passwordParameter);
        }
    
        public virtual int UpdateReservationStatus(Nullable<int> reservationId, string newStatus)
        {
            var reservationIdParameter = reservationId.HasValue ?
                new ObjectParameter("ReservationId", reservationId) :
                new ObjectParameter("ReservationId", typeof(int));
    
            var newStatusParameter = newStatus != null ?
                new ObjectParameter("NewStatus", newStatus) :
                new ObjectParameter("NewStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateReservationStatus", reservationIdParameter, newStatusParameter);
        }
    }
}
