//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace housemanagement1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public string CardHolderName { get; set; }
        public Nullable<int> PaymentAmount { get; set; }
        public string ExpiryMonth { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    }
}
