//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace housemanagement1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int ReservationId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> ReserveDate { get; set; }
        public string Status { get; set; }
    }
}
